name: Deploy Farasite Next.js to Ubuntu Server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "🚀 Starting Farasite deployment..."

            # رفتن به مسیر اصلی سرور
            cd /var/www/

            # پاک کردن پوشه قبلی
            rm -rf isatis_undermaintenance
            mkdir -p isatis_undermaintenance
            cd isatis_undermaintenance

            # کلون کردن آخرین نسخه از پروژه
            echo "📥 Cloning latest Farasite repository..."
            git clone --depth 1 https://github.com/isatispooya/isatis-500.git . || { echo "❌ Git clone failed"; exit 1; }

            # نصب پکیج‌ها
            echo "📦 Installing dependencies..."
            rm -rf node_modules package-lock.json
            npm install || { echo "❌ npm install failed"; exit 1; }

            # بیلد پروژه
            echo "🔨 Building the Next.js app..."
            npm run build || { echo "❌ Build failed"; exit 1; }

            # ریستارت سرویس PM2 روی پورت 9090
            echo "♻️ Restarting PM2 process on port 9090..."

            pm2 delete isatis_undermaintenance || echo "ℹ️ No existing PM2 process found"
            NODE_ENV=production NODE_NO_WARNINGS=1 pm2 start "npm run start -- -p 9090" --name isatis_undermaintenance || { echo "❌ PM2 start failed"; exit 1; }

            # ذخیره وضعیت PM2
            pm2 save || { echo "❌ PM2 save failed"; exit 1; }

            echo "✅ Farasite deployment completed successfully on port 9090"